/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/Home` | `/frontend/Home`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/about` | `/frontend/about`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/lifts` | `/frontend/lifts`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/profile` | `/frontend/profile`; params?: Router.UnknownInputParams; } | { pathname: `/frontend/components/bottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/frontend${'/(tabs)'}/Home` | `/frontend/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/frontend${'/(tabs)'}/about` | `/frontend/about`; params?: Router.UnknownOutputParams; } | { pathname: `/frontend${'/(tabs)'}/lifts` | `/frontend/lifts`; params?: Router.UnknownOutputParams; } | { pathname: `/frontend${'/(tabs)'}/profile` | `/frontend/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/frontend/components/bottomNav`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/frontend${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/frontend/Home${`?${string}` | `#${string}` | ''}` | `/frontend${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/frontend/about${`?${string}` | `#${string}` | ''}` | `/frontend${'/(tabs)'}/lifts${`?${string}` | `#${string}` | ''}` | `/frontend/lifts${`?${string}` | `#${string}` | ''}` | `/frontend${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/frontend/profile${`?${string}` | `#${string}` | ''}` | `/frontend/components/bottomNav${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/Home` | `/frontend/Home`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/about` | `/frontend/about`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/lifts` | `/frontend/lifts`; params?: Router.UnknownInputParams; } | { pathname: `/frontend${'/(tabs)'}/profile` | `/frontend/profile`; params?: Router.UnknownInputParams; } | { pathname: `/frontend/components/bottomNav`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
